POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name":"abc",
    "email":"abc@epitometrc.com",
    "username":"test-user-2",
    "password":"test_pass",
    "role":"super-admin"
}

###login

POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "username":"test-user-2",
    "password":"password1"
}

###authorization
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QtdXNlci0yIiwiaWF0IjoxNjg5ODYyODc5LCJleHAiOjE2ODk4NjM3Nzl9.mCcrwnec2MW9b42RrbpnqiTt6bomHxH1pn6N2qQrS5g
###password-resett
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"abc@epitometrc.com"
}


###update password end-point
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":"abc@epitometrc.com",
    "pin":"448056",
    "newPassword":"password1"
}

###logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QtdXNlci0yIiwiaWF0IjoxNjg5ODY0MDkwLCJleHAiOjE2ODk4NjU4OTB9.DLPBEn0oQE-6nQPUDP4WuK9UNC2o3T0BVb4Fni3SyaU